Added Spanish PREFILL
G6EJD/ESP32_Advanced_Weather_Server pull request #2
Opened 2020-10-04 20:48 UTC by deltazerorsan

The main interface, as planned by David, can now be charged in English or Spanish.

2020-10-04 21:27 UTC, deltazerorsan commented
This is the new approach. Maybe there is no need to close the previous pull...

2020-10-04 21:50 UTC, jsvaliente commented on Prefill_ES.ino
> +  TXT_WED             = "Mie";
Missing accent. It should be 'Mié'.

2020-10-04 21:51 UTC, jsvaliente commented on Prefill_ES.ino
> +  TXT_SAT             = "Sab";
Missing accent. It should be 'Sáb'.

2020-10-04 21:51 UTC, jsvaliente commented on Prefill_ES.ino
> +  TXT_WCHILL_HINDEX   = "Sensación térmica / Indice de calor";
Missing accent. It should be 'Sensación térmica / Índice de calor'.

2020-10-05 08:38 UTC, deltazerorsan commented
Thanks Javier.

¿Podrías revisar la traducción de "Feelslike" y "Windchill"? ¿Tenemos términos en español diferentes para esos en Inglés?

(Could you check the translation of "Feelslike" and "Windchill"? Do we have different Spanish terms for those in English?)

2020-10-05 09:33 UTC, G6EJD commented
1. You need to remove prefill_EN() from sketch.
2. Rename prefill_ES.ino to prefill_ES.**h**
3. Add at the start #include "prefill_ES.h"
4. Make sure prefill_ES.h is in the sketch folder

2020-10-05 21:00 UTC, deltazerorsan commented
Hi Dave,

The .h approach is not easy because the compiler need to know the functions first before using them.

I see not very functional to declare prototypes to solve that so at last my solution is to use conditional compilation.

It works, but tell me if you hate that solution.

Roman

2020-10-06 07:21 UTC, G6EJD requested changes
The best way to do this is use #include statements.
1. ESP32_OWM...ino 
2. Prefill_EN.h
3. Prefill_ES.h
4. Prefill_DE.h. And so on with others

Now just add the include as required:
//#include “prefill_EN.h
#include “prefill_ES.h”

And remove the prefill_EN() function from the main source code
What about the html menu items still in EN ?

2020-10-07 11:20 UTC, deltazerorsan commented
Hi Dave,

The conversion to .h is not straight forward because you break the rule "first declare, then use" due that the Prefill function call another three functions from inside the function it self. That can be solver declaring prototypes before the include statement but that does not solve the Help page...

I'm looking for another approach...

Yours, Roman

2020-10-07 15:23 UTC, jsvaliente commented
Shouldn't the .h file corresponding to the pre-fill match somehow the "String Language” variable from “own_credentials.h” (or viceversa). Just sayin’….

2020-10-07 17:45 UTC, deltazerorsan commented
> Shouldn't the .h file corresponding to the pre-fill match somehow the "String Language” variable from “own_credentials.h” (or viceversa). Just sayin’….

Yes, not bad idea, but first things first.

Really the include statement can be inside own_credentials.h so there is only one place to touch...

2020-10-08 11:07 UTC, G6EJD commented
Try this one:
https://github.com/G6EJD/ESP32_Advanced_Weather_Server V3

you need ‘credentials_EN.h’

2020-10-10 18:06 UTC, deltazerorsan commented
This is. Take a look at the screenshot.

2020-10-21 16:57 UTC, G6EJD commented
There is too much change for me to see through this, I can approve credentials_es.h

2020-10-22 16:21 UTC, deltazerorsan commented
I'll try to simplify this ... I can't promise anything.

2020-10-22 17:24 UTC, deltazerorsan commented
Dave,

Please try to merge now. If in doubt I can close this pull an start over...

My apologizes for the inconveniences.

Roman

2020-10-22 18:04 UTC, merged

2020-10-22 18:06 UTC, G6EJD commented
That worked, thank you for doing this

2020-10-22 20:08 UTC, deltazerorsan commented
A pleasure!